# tools/web_project_zipper.py

import os
import zipfile

def main():
    """
    Creates a basic web project (index.html, styles.css, script.js)
    and zips it into a single archive.
    """
    print("--- Web Project Zipper ---")

    project_name = input("Enter the name for your web project (e.g., 'MyWebsite'): ").strip()
    if not project_name:
        print("Project name cannot be empty. Aborting.")
        return

    project_dir = project_name # Use project name as the directory name
    zip_filename = f"{project_name}.zip"

    print(f"\nCreating web project '{project_name}' in directory '{project_dir}'...")

    try:
        # Create project directory
        os.makedirs(project_dir, exist_ok=True)
        print(f"  Created directory: {project_dir}/")

        # Create index.html
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <h1>Welcome to {project_name}!</h1>
    <p>This is a basic HTML file generated by H7T.</p>
    <button id="myButton">Click Me!</button>
    <script src="script.js"></script>
</body>
</html>"""
        html_path = os.path.join(project_dir, 'index.html')
        with open(html_path, 'w') as f:
            f.write(html_content)
        print(f"  Created file: {project_dir}/index.html")

        # Create styles.css
        css_content = """body {
    font-family: sans-serif;
    margin: 20px;
    background-color: #f4f4f4;
    color: #333;
}
h1 {
    color: #0056b3;
}
button {
    padding: 10px 15px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}
button:hover {
    background-color: #0056b3;
}"""
        css_path = os.path.join(project_dir, 'styles.css')
        with open(css_path, 'w') as f:
            f.write(css_content)
        print(f"  Created file: {project_dir}/styles.css")

        # Create script.js
        js_content = """document.getElementById('myButton').addEventListener('click', function() {
    alert('Button clicked! This is from script.js');
});

console.log('script.js loaded!');"""
        js_path = os.path.join(project_dir, 'script.js')
        with open(js_path, 'w') as f:
            f.write(js_content)
        print(f"  Created file: {project_dir}/script.js")

        # Create the zip archive
        print(f"\nZipping project into '{zip_filename}'...")
        with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zf:
            for root, _, files in os.walk(project_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    # Arcname is the path inside the zip file
                    arcname = os.path.relpath(file_path, os.path.dirname(project_dir))
                    zf.write(file_path, arcname)
        print(f"Successfully created zip archive: {zip_filename}")
        print(f"Project directory '{project_dir}' is still present.")


    except Exception as e:
        print(f"An error occurred during web project creation or zipping: {e}")

# Do NOT call main() here. H7T does that automatically.
